### PR TITLE
implement

### PR DESCRIPTION
**Pull request by divszz**
## Description
Implementation of GitHub actions for tcet-linux-neofetch repository

## Screenshots (if applicable)
N/A

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Review by harshau007 — CHANGES_REQUESTED** [review]
File structure should be `.github/workflows/release.yml`

**Review by Rishabh672003 — APPROVED** [review]
looks good

**Review by harshau007 — APPROVED** [review]
LGTM!!!

**Review by Akash6222 — APPROVED** [review]
GTG

**Pull request merged**
